//registration
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

//login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

//updates
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'
export const UPDATE_IMAGE_SUCCESS = 'UPDATE_IMAGE_FAIL'
export const UPDATE_IMAGE_FAIL = 'UPDATE_IMAGE_FAIL'

//recovery
export const RECOVERY_SUCCESS = 'RECOVERY_SUCCESS'
export const RECOVERY_FAIL = 'RECOVERY_FAIL'

//reset
export const RESET_SUCCESS = 'RESET_SUCCESS'
export const RESET_FAIL = 'RESET_FAIL'

//logout
export const LOGOUT = 'LOGOUT'

//Data acquisition
export const GET_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const GET_USER_FAIL = 'LOAD_USER_FAIL'
export const GET_FORUM_SUCCESS = 'GET_FORUM_SUCCESS'
export const GET_FORUM_FAIL = 'GET_FORUM_FAIL'
export const GET_USERS_SUCCCESS = 'GET_USERS_SUCCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'

//Data transmission
export const SEND_POST_SUCCESS = 'SEND_POST_SUCCESS'
export const SEND_POST_FAIL = 'SEND_POST_FAIL'

//Deletion
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS'
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL'
export const DELETE_POST_SUCCESS = 'SEND_POST_SUCCESS'
export const DELETE_POST_FAIL = 'SEND_POST_FAIL'
export const ELEVATE_SUCCESS = 'ELEVATE_SUCCESS'
export const ELEVATE_FAIL = 'ELEVATE_FAIL'
